### ISSUE TITLE
panic: json: cannot unmarshal number into Go struct field Image.ImageSize of type string

### ISSUE THREAD

**Issue by tomatopotatocn** [TencentCloud/tencentcloud-sdk-go#1]
when i call the DescribeImages API,it returns a error

` package main
 
 import (
         "fmt"
 
         "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common"
         "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors"
         "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile"
         cvm "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm/v20170312"
 )
 
 func main() {
         // 实例化一个认证对象，入参需要传入腾讯云账户secretId，secretKey
         credential := common.NewCredential(
                 "myid",
                 "mykey",
         )
 
         // 实例化一个客户端配置对象，可以指定超时时间等配置
         cpf := profile.NewClientProfile()
         cpf.HttpProfile.ReqMethod = "GET"
         cpf.HttpProfile.ReqTimeout = 5
         cpf.SignMethod = "HmacSHA1"
 
         // 实例化要请求产品(以cvm为例)的client对象
         client, _ := cvm.NewClient(credential, "ap-beijing", cpf)
         // 实例化一个请求对象，根据调用的接口和实际情况，可以进一步设置请求参数
         request := cvm.NewDescribeImagesRequest()
         // 通过client对象调用想要访问的接口，需要传入请求对象
         response, err := client.DescribeImages(request)
         // 处理异常
         if _, ok := err.(*errors.TencentCloudSDKError); ok {
                 fmt.Printf("An API error has returned: %s", err)
                 return
         }
         // unexpected errors
         if err != nil {
                 panic(err)
         }
         // 打印返回的json字符串
         fmt.Printf("%s", response.ToJsonString())
 }
`

return is  as follows:

panic: json: cannot unmarshal number into Go struct field Image.ImageSize of type string

goroutine 1 [running]:
main.main()
	/home/ubuntu/go/src/hcm/images.go:38 +0x57d
exit status 2

**Comment by zqfan** [comment]
fixed by https://github.com/TencentCloud/tencentcloud-sdk-go/commit/abd8ffd9ca03cf15a8074d23796c4cf393fd944d
