### ISSUE TITLE
结构体成员为什么要定义成指针呢?

### ISSUE THREAD

**Issue by tfzxyinhao** [TencentCloud/tencentcloud-sdk-go#10]
![image](https://user-images.githubusercontent.com/444814/43832204-37a51950-9b39-11e8-9375-aa9d4c5c017a.png)

**Comment by tfzxyinhao** [comment]
使用时 每个成员都要先定义一个变量 然后取地址

**Comment by unlikezy** [comment]
确实没必要. pb3.0的所有数值/字符串变量都已经是直接用原生的了.

**Comment by zqfan** [comment]
原因有很多，其中比较直接的一个是：难以判定该字段是否有值。例如有个字段Size是int型的，接口没有定义这个字段的默认值（这种情况很普遍），这个字段是可选的。在发送请求时，如果这个字段不是指针，那么Size=0就无从判定是用户赋值的，还是语言默认值。如果类型是int指针，就能够处理了。
