### ISSUE TITLE
go mod tidy 出现问题

### ISSUE THREAD

**Issue by mayunmeiyouming** [TencentCloud/tencentcloud-sdk-go#102]
github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/ses/v20201002: package provided by github.com/tencentcloud/tencentcloud-sdk-go at latest version v1.0.69 but not at required version v3.0.233+incompatible

**Comment by zqfan** [comment]
最新版本已解决这个问题，请参考readme中的有关说明
