### ISSUE TITLE
go get module issue

### ISSUE THREAD

**Issue by yagrxu** [TencentCloud/tencentcloud-sdk-go#108]
when I ran `go get module`, nothing happens. Then I realized the URL in macOS should be capitalized [TencentCloud](https://github.com/TencentCloud/tencentcloud-sdk-go/issues/new) for , but module definition in go.mod is in small letter.

Could you please check this?

**Comment by vincenthcui** [comment]
```bash
➜  go get -v github.com/tencentcloud/tencentcloud-sdk-go@latest
go: downloading github.com/tencentcloud/tencentcloud-sdk-go v1.0.108
go: github.com/tencentcloud/tencentcloud-sdk-go latest => v1.0.108
github.com/tencentcloud/tencentcloud-sdk-go
```

@yagrxu  LGTM

**Comment by zqfan** [comment]
github server actually treats URL (the path part) case insensitive, so it should work in any OS.
I'm not sure what the real problem is, you can use debug mode or add verbose option (-v) for go get to print more information
