### ISSUE TITLE
HTTP support, in addition to HTTPS

### ISSUE THREAD

**Issue by KEVISONG** [TencentCloud/tencentcloud-sdk-go#109]
Hi

Is it possible to support HTTP profile in: 

[https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/common/profile/http_profile.go](https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/common/profile/http_profile.go)

Right now only HTTPS scheme is supported, shown below:

```go
func NewHttpProfile() *HttpProfile {
	return &HttpProfile{
		ReqMethod:  "POST",
		ReqTimeout: 60,
		Scheme:     "HTTPS",
		RootDomain: "",
		Endpoint:   "",
	}
}
```

Is it possible to add a func to return HTTP scheme like below?

```go
// Newly added HTTP profile
func NewHttpProfile() *HttpProfile {
	return &HttpProfile{
		ReqMethod:  "POST",
		ReqTimeout: 60,
		Scheme:     "HTTP",
		RootDomain: "",
		Endpoint:   "",
	}
}
// Original HTTPS profile
func NewHttpsProfile() *HttpProfile {
	return &HttpProfile{
		ReqMethod:  "POST",
		ReqTimeout: 60,
		Scheme:     "HTTPS",
		RootDomain: "",
		Endpoint:   "",
	}
}
```

**Comment by zqfan** [comment]
It is useful for some special scenarios, but API only accepts https requests in public cloud service.
Scheme is a public attribute, you can just modify it, or construct a new one.
