### ISSUE TITLE
那么vod服务应该怎么使用?

### ISSUE THREAD

**Issue by JavinYang** [TencentCloud/tencentcloud-sdk-go#11]
能不能给个vod的例子?

**Comment by zqfan** [comment]
vod尚未接入API3.0，所以SDK中无法使用vod服务

**Comment by mxy1973** [comment]
现在接API3.0了，作为一个自学的初学者，照着弄，还是有很多地方不懂不会呀，可以给个联系方式吗？ＱＱ，微信，邮箱都可以

**Comment by zqfan** [comment]
@mxy1973 可以尝试使用API Explorer工具先熟悉下https://console.cloud.tencent.com/api/explorer?Product=vod
