### ISSUE TITLE
创建lb指定标签key，value留空报错

### ISSUE THREAD

**Issue by ioito** [TencentCloud/tencentcloud-sdk-go#110]
请把 tencentcloud/common/http/request.go 第110行判断去掉，否则报错:

[TencentCloudSDKError] Code=InvalidParameterValue, Message=参数`Tags`中`[{'TagKey': 'app_name', 'TagValue': 'cmdb'}, {'TagKey': 'bucket-name', 'TagValue': 'wangwenlong'}, {'TagKey': 'business'}]`不合规范, RequestId=53823ae5-01c3-4088-8a4a-d4cba7ed9330

**Comment by zqfan** [comment]
当前版本110行和你这个没有关系，你用的版本是多少？
通常这样的报错是产品服务返回的，意味着接口不允许这种传值

**Comment by ioito** [comment]
GetUrlQueriesEncoded函数里面第三行，即使value为空，也需要传 'TagValue’: ''

**Comment by zqfan** [comment]
不支持空字符串，如果要传，请使用签名方法v3用post json方式发送
