### ISSUE TITLE
4.27的提交貌似编不过？

### ISSUE THREAD

**Issue by meowovo** [TencentCloud/tencentcloud-sdk-go#112]
../.gvm/pkgsets/go1.14.4/global/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v1.0.144/tencentcloud/cdb/v20170320/models.go:81:10: syntax error: unexpected %, expecting type
../.gvm/pkgsets/go1.14.4/global/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v1.0.144/tencentcloud/cdb/v20170320/models.go:83:5: syntax error: non-declaration statement outside function body
../.gvm/pkgsets/go1.14.4/global/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v1.0.144/tencentcloud/cdb/v20170320/models.go:116:10: syntax error: unexpected %, expecting type
../.gvm/pkgsets/go1.14.4/global/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v1.0.144/tencentcloud/cdb/v20170320/models.go:118:5: syntax error: non-declaration statement outside function body
../.gvm/pkgsets/go1.14.4/global/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v1.0.144/tencentcloud/cdb/v20170320/models.go:140:10: syntax error: unexpected %, expecting type
../.gvm/pkgsets/go1.14.4/global/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v1.0.144/tencentcloud/cdb/v20170320/models.go:142:5: syntax error: non-declaration statement outside function body
../.gvm/pkgsets/go1.14.4/global/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v1.0.144/tencentcloud/cdb/v20170320/models.go:170:10: syntax error: unexpected %, expecting type
../.gvm/pkgsets/go1.14.4/global/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v1.0.144/tencentcloud/cdb/v20170320/models.go:172:5: syntax error: non-declaration statement outside function body
../.gvm/pkgsets/go1.14.4/global/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v1.0.144/tencentcloud/cdb/v20170320/models.go:422:10: syntax error: unexpected %, expecting type
../.gvm/pkgsets/go1.14.4/global/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v1.0.144/tencentcloud/cdb/v20170320/models.go:424:5: syntax error: non-declaration statement outside function body
../.gvm/pkgsets/go1.14.4/global/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go@v1.0.144/tencentcloud/cdb/v20170320/models.go:424:5: too many errors

**Comment by zqfan** [comment]
抱歉，因为我的工作疏漏导致了问题，已经修复了，请使用最新的版本。
后续我们增加发布前的检查，避免类似的低级错误出现。
