### ISSUE TITLE
Latest tag doesn't point at latest real version

### ISSUE THREAD

**Issue by jeffwidman** [TencentCloud/tencentcloud-sdk-go#113]
When I look at https://github.com/TencentCloud/tencentcloud-sdk-go, the "latest version" on the right hand sidebar lists 3.0.10.

The latest appears to actually be `v1.0.x`: https://github.com/TencentCloud/tencentcloud-sdk-go/releases

Please update the `latest` tag to point at that so that it's easier to see what is actually the latest release.

**Comment by zqfan** [comment]
the bot just tag new update, but no release is created, those release information is manually created long time ago.
they are deleted now, please just refer to the tags
