### ISSUE TITLE
struct field tag incompatible when using go vet

### ISSUE THREAD

**Issue by KEVISONG** [TencentCloud/tencentcloud-sdk-go#119]
Hi Team

When the sdk is imported in go project, the `go vet` check fails and returns the following error message:

```
struct field tag `json:"DataPoints,omitempty" name:"DataPoints" list` not compatible with reflect.StructTag.Get: bad syntax for struct tag pair
```

When `list` is removed in the [struct field tag](https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/monitor/v20180724/models.go#L3789), the error disappears.

```go
DataPoints []*DataPoint `json:"DataPoints,omitempty" name:"DataPoints" list` // go vet returns error
```
```go
DataPoints []*DataPoint `json:"DataPoints,omitempty" name:"DataPoints"` // pass all checks
```

What are the considerations of adding `list` in the struct field tag? Would it be better to remove it (if not affecting it's functionalities) for cleaner and more conventional code style? : )

**Comment by zqfan** [comment]
It's used to indicate that this field is an array list, and it is useful in the old versions.
I think it can be removed for now, will be done in next release
