### ISSUE TITLE
创建子网失败

### ISSUE THREAD

**Issue by yangwanli2017** [TencentCloud/tencentcloud-sdk-go#12]
panic: json: cannot unmarshal number into Go struct field Subnet.Zone of type string

接口调用返回值里面的Zone是数字
{
 "Response": {
        "Subnet": {
            "VpcId": "vpc-123456",
            "IsDefault": false,
            "SubnetName": "myvpc-subnet123456",
            "Zone": 160002,
            "SubnetId": "subnet-123456",
            "CidrBlock": "10.0.1.0/24",
            "AvailableIpAddressCount": 253
        },
        "RequestId": "9570e58b5-8753-4936-8901-e0791468a087"
    }
}

**Comment by zqfan** [comment]
经确认，后台已修复这个问题，现在Zone会返回字符串，例如ap-guangzhou-3这种
