### ISSUE TITLE
Go mod breakage from most recent update

### ISSUE THREAD

**Issue by ChrisPenner** [TencentCloud/tencentcloud-sdk-go#125]
Looks like the most recent changes to the top-level go mod have broken downstream dependencies. 
E.g. https://github.com/hashicorp/terraform  can no longer `go mod vendor` successfully.

```
terraform> go mod vendor
go: github.com/tencentcloud/tencentcloud-sdk-go@v3.0.82+incompatible: reading github.com/tencentcloud/tencentcloud-sdk-go/go.mod at revision v3.0.82: unknown revision v3.0.82
```

**Comment by tony612** [comment]
I also got this problem. Dear maintainers, please don't delete an old tag without thinking.
