### ISSUE TITLE
There is a bug in billing sdk DescribeCostDetail

### ISSUE THREAD

**Issue by kitianFresh** [TencentCloud/tencentcloud-sdk-go#127]
E0630 16:22:37.289374   64714 log.go:17] [Error] tencent cloud api failed, retrying 1 times, err: [TencentCloudSDKError] Code=ClientError.ParseJsonError, Message=Fail to parse json content: {"Response":{"DetailSet":[],"Total":"23","RequestId":"1561f25c-3cb2-43ca-af18-197a7ad66b79"}}, because: json: cannot unmarshal string into Go struct field .Response.Total of type uint64, RequestId=

the struct Total field is uint64, but return is an string

when your request param needRecordNum  = 1, then it will return string, needRecordNum =0, it is ok

@likexian @longkai @xbkaishui @zqfan @u2takey

**Comment by zqfan** [comment]
please go to console.tencent.cloud.com and report a ticket to billing product, is their responsibility to keep the response behaving as the document promised.

**Comment by xwh0809** [comment]
Thanks for the feedback, your issue has been fixed.
