### ISSUE TITLE
client的初始化逻辑是否不合理？

### ISSUE THREAD

**Issue by linhongzhao321** [TencentCloud/tencentcloud-sdk-go#129]
### 问题 

client的初始化逻辑是否不合理？

### 背景

1. region不是必填参数，或者说**不是所有sdk模块都必填**的参数，但在对应的初始化方法中是必填选项
    > 参考  https://cloud.tencent.com/document/api/1110/36920 中关于 region 的描述

2. common/Client.httpClient 是必填参数

3. 基于上述  1. 和 2. 的原因，在 common/client.go 中，Client.region 属性和 Client.httpClient 属性被一起放在 Client.Init() 方法中执行。相当于必填参数与非必填参数放在一起初始化，**让非必填参数成为必填参数**。这设计本身似乎不合理？
     ![image](https://user-images.githubusercontent.com/33045301/124209718-a3e20d00-db1c-11eb-8c3d-972fb74648e6.png)

### 目标

让 region 在非必填的时候**可以选择**不填

### 建议

common/Client.region 的初始化与 common/Client.httpClient 的初始化逻辑分离

1. 为region提供独立的设置方法

2. 对于region必填的模块/接口。默认调度上述方法或检测未初始化则报错（个人建议后者，开发者通过文档或发版前测试都能直接发现问题）

**Comment by zqfan** [comment]
sdk除了common外都是生成的代码，在common里是判断不出接口是否需要填写region的，甚至同一个产品里的接口有的可能必填，有的不是必填。必填时不填则会报错，不必填时填了不会有啥影响。实在懒得写就传空字符串吧

**Comment by linhongzhao321** [comment]
> sdk除了common外都是生成的代码，在common里是判断不出接口是否需要填写region的，甚至同一个产品里的接口有的可能必填，有的不是必填。必填时不填则会报错，不必填时填了不会有啥影响。实在懒得写就传空字符串吧

嗯，忘了更新了。后来又多接了两个服务，大概理解你们sdk的做法了。
