### ISSUE TITLE
[TencentCloudSDKError] Code=ClientError.NetworkError, Message=Fail to get response because Post "https://sms.tencentcloudapi.com/": EOF, RequestId=	

### ISSUE THREAD

**Issue by liusiming0001** [TencentCloud/tencentcloud-sdk-go#131]
[TencentCloudSDKError] Code=ClientError.NetworkError, Message=Fail to get response because Post "https://sms.tencentcloudapi.com/": EOF, RequestId=	

这个eof错误如何处理，请求是否达到服务器？是否可以重试？

**Comment by zqfan** [comment]
请求可能已经到达服务器，如果接口不是幂等的，慎重重试。
如果发现是时间周期或者固定调用次数后就会发生的错误，一般是服务器主动关闭连接导致的，如果想避免这种情况，可以关闭长连接。如果随机出现，则可能是网络问题，此时非幂等接口重试可能会有问题
