### ISSUE TITLE
Invalid LoadBalancerId

### ISSUE THREAD

**Issue by wanglong001** [TencentCloud/tencentcloud-sdk-go#135]
1. 使用 DescribeLoadBalancers 获取了 所有的LoadBlalance，得到 LoadBalanceId
![image](https://user-images.githubusercontent.com/14817376/126440801-0527e6d1-0b9f-4cf9-bde7-b34611f2b7e8.png)
![image](https://user-images.githubusercontent.com/14817376/126440902-3138b8da-fce8-476e-8844-c862f3ccf791.png)

2. 再用 LoadBalanceId 获取 NewDescribeClassicalLBListenersRequest， 结果出现：

```
err=[TencentCloudSDKError] Code=InvalidParameter, Message=Invalid LoadBalancerId, LoadBalancerId: lb-edoyvlkz, RequestId=db6fc89f-2d2d-47f8-98a2-6ccad0f051a6
```

**Comment by zqfan** [comment]
这个报错是clb后端返回的，并非SDK的报错，如有需要可以到控制台提工单给clb产品。
从报错看，可能lb并不存在（或者不在请求的地域中存在）
