### ISSUE TITLE
求刷新cdn的sdk

### ISSUE THREAD

**Issue by wudiliujie** [TencentCloud/tencentcloud-sdk-go#14]
求刷新cdn的sdk

**Comment by zqfan** [comment]
cdn并未支持api3.0，因此sdk无法包含。请在控制台工单系统提单给cdn产品要求cdn支持api3.0

**Comment by zqfan** [comment]
cdn已经发布了少量接口，https://github.com/TencentCloud/tencentcloud-sdk-go/tree/master/tencentcloud/cdn/v20180606
但我不清楚这些是否够用
请在控制台工单系统提单给cdn产品要求cdn将全量的接口都支持api3.0
