### ISSUE TITLE
init.go  os.ReadFile 

### ISSUE THREAD

**Issue by harrisHxy** [TencentCloud/tencentcloud-sdk-go#140]
![image](https://user-images.githubusercontent.com/10279244/127336511-0b82d98c-5940-4ceb-8323-1c6aa4790b4a.png)

**Comment by zqfan** [comment]
yes, https://github.com/TencentCloud/tencentcloud-sdk-go/pull/137 introduces this problem, and our test environment is just running go1.16 so it is not found during integration test.
will be fixed in next release.
