### ISSUE TITLE
调用 ckafka 包下的 DescribeTopicDetail 接口时，出现 json 转换错误

### ISSUE THREAD

**Issue by eviltomorrow** [TencentCloud/tencentcloud-sdk-go#148]
在调用 ckafka 的 DescribeTopicDetail 接口时，出现 because: json: cannot unmarshal string into Go struct field TopicRetentionTimeConfigRsp.Response.Result.TopicList.RetentionTimeConfig.ModTimeStamp of type int64 错误
#149

**Comment by zqfan** [comment]
这说明接口的返回和定义不符合, 请到控制台工单系统提工单给ckafka产品反馈, 
sdk是根据业务接口在官网的说明生成的,直接修改是无效的,下次发版本就又会被覆盖
