### ISSUE TITLE
struct field triggered warning when using golangci-lint

### ISSUE THREAD

**Issue by KEVISONG** [TencentCloud/tencentcloud-sdk-go#155]
Hi Team

For struct field in https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/monitor/v20180724/models.go#L3827

It will trigger a warning when using `golangci-lint` shown as below

![3ecd917e0eacbd5728454493c044b4d](https://user-images.githubusercontent.com/39701004/134752379-23757958-d4ee-4a87-b7f7-bf5775e82d2e.png)

### Current behavior: field defined as `RequestId`

```go
RequestId *string `json:"RequestId,omitempty" name:"RequestId"`
```

### Expoected behavior: field defined as `RequestID`

```go
RequestID *string `json:"RequestId,omitempty" name:"RequestId"`
```

In this way, the code will pass the lint check.

**Comment by zqfan** [comment]
unfortunately, the API has already defined it as RequestId, SDK should keep the same as it. For compatibility, SDK can not change it. And SDK should be required as a vendor, you can set lint to ignore vendor directory
