### ISSUE TITLE
提问： CODING 项目管理【云服务】

### ISSUE THREAD

**Issue by wanglong001** [TencentCloud/tencentcloud-sdk-go#160]
请问下， https://cloud.tencent.com/document/product/1113/36819 这类API 有**go**的sdk吗？
我暂时找不到，我需要 当前repo 代码风格的client， 保持兼容性
谢谢

**Comment by zqfan** [comment]
链接里面的内容和当前的提问不知道有什么关联啊，是链接给错了吗？

**Comment by wanglong001** [comment]
@zqfan 
sorry， 这个 https://help.coding.net/openapi#c7577478c0cae7875707ffbb4d864ed2

**Comment by zqfan** [comment]
虽然接口风格和云API3.0很像，但是实际并不是云API3.0的，也就不会包含在这个SDK里了。
理论上如果想，他们是可以提供类似此仓库风格的SDK，但我不确定他们是否已经提供了，从链接里看不出来

**Comment by wanglong001** [comment]
好的， 谢谢！ @zqfan
