### ISSUE TITLE
undefined: "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common".CredentialIface 

### ISSUE THREAD

**Issue by hcf1425** [TencentCloud/tencentcloud-sdk-go#161]
while I using tdmq API, I encounter the following error:
../../../../../go/pkg/mod/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tdmq@v1.0.298/v20200217/client.go:37:27: undefined: "github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common".CredentialIface

**Comment by zqfan** [comment]
it might caused by out dated github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common, newer version of tdmq uses a new feature in common package.

**Comment by sesky4** [comment]
try update to latest version:
```
go get -u github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common
go get -u github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/tdmq
```
