### ISSUE TITLE
CloudAudit service response missing field

### ISSUE THREAD

**Issue by Kuanming3** [TencentCloud/tencentcloud-sdk-go#166]
Problem: CloudAudit response missing field `TotalCount`

According to  [https://intl.cloud.tencent.com/document/api/1021/42703](url) , there is supposed to have `TotalCount` in the response from the latest version。 However currently the response does not include the field 

Can I know when will it be included with the latest update?

**Comment by zqfan** [comment]
please go to tencentcloud management console and open a ticket to CloudAudit team, thanks

**Comment by zqfan** [comment]
https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/cloudaudit/v20190319/models.go#L367
