### ISSUE TITLE
[TencentCloudSDKError] Code=ClientError.NetworkError: no route to host

### ISSUE THREAD

**Issue by gushitong** [TencentCloud/tencentcloud-sdk-go#168]
[TencentCloudSDKError] Code=ClientError.NetworkError, Message=Fail to get response because Post "https://cloud.tencentcloudapi.com/": dial tcp 0.0.0.1:443: connect: no route to hostERRO[0010] [TencentCloudSDKError] Code=ClientError.NetworkError, Message=Fail to get response because Post "https://cloud.tencentcloudapi.com/": dial tcp 0.0.0.1:443: connect: no route to host  mobile_number=186xxxx0251 security_code=177918

**Comment by gushitong** [comment]
IP 地址查询结果：

**Comment by zqfan** [comment]
为什么要把endpoint填成cloud.tencentcloudapi.com这个地址？这个域名本身就不存在啊，也并没有任何一个产品在使用这个域名

**Comment by gushitong** [comment]
已经改到新的域名了，多谢
