### ISSUE TITLE
SCF 调用Invoke BaseRequest 为nil 怎么初始化BaseRequest 的？

### ISSUE THREAD

**Issue by jjjachyty** [TencentCloud/tencentcloud-sdk-go#176]
func (r *BaseRequest) GetScheme() string {
	return r.scheme
}
报空指针

**Comment by zqfan** [comment]
避免直接使用baserequest，使用对应接口的初试化方法得到request实例，例如NewInvokeRequest() https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/scf/v20180416/client.go#L1931
