### ISSUE TITLE
common v0.0.0？

### ISSUE THREAD

**Issue by YellowBroke** [TencentCloud/tencentcloud-sdk-go#178]
![image](https://user-images.githubusercontent.com/52766743/154190869-e9fe4c60-15ec-484d-ae60-b1291c1c38cf.png)

**Comment by sesky4** [comment]
this is a bug, we will fix it soon
you can use older version as workground: 
`go get -u github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cdb@v1.0.345`

**Comment by sesky4** [comment]
@YellowBroke  solved
