### ISSUE TITLE
全球复制组删除接口的response的taskId类型

### ISSUE THREAD

**Issue by BrotherGao** [TencentCloud/tencentcloud-sdk-go#179]
https://github.com/TencentCloud/tencentcloud-sdk-go/blob/cd9d089cee678678299132cf10065aac28bac57a/tencentcloud/redis/v20180412/models.go#L918
其他任务response的TaskId都是`*int64`，为啥到了这个接口变成`*float64`?这个设计是什么其他用途吗？

**Comment by sesky4** [comment]
@BrotherGao  sorry，应该是当时设计接口的一个错误，但是现在因为已经发布在用了，修改类型会破坏兼容性，所以没办法修改了
