### ISSUE TITLE
v1版本如何指定CpuTopology

### ISSUE THREAD

**Issue by speauty** [TencentCloud/tencentcloud-sdk-go#182]
据v3版本，有该cvm.CpuTopology参数，在创建实例的时候，由于采用go mod管理后，导致tags回退到v1。经比对，已无该参数。

**Comment by zqfan** [comment]
请贴一下你使用的v3版本号，我去查一下。通常我们是不允许不兼容的参数修改的，v3到v1只是tag变化，接口的参数还是维持兼容的。

**Comment by zqfan** [comment]
https://cloud.tencent.com/document/product/213/15695
这里有完整的该产品变更历史，里面没有CpuTopology变更的历史

**Comment by speauty** [comment]
RunInstancesRequest.CpuTopology

> 请贴一下你使用的v3版本号，我去查一下。通常我们是不允许不兼容的参数修改的，v3到v1只是tag变化，接口的参数还是维持兼容的。

确实存在一个 CpuTopology的结构体，挂到了RunInstancesRequest下面
```
// cpu白名单
RunInstancesRequest.CpuTopology *CpuTopology `json:"CpuTopology,omitempty" name:"CpuTopology"`
type CpuTopology struct {
	// CPUBAIMD
	Architecture *string `json:"Architecture,omitempty" name:"Architecture"`
}
```
至于具体在v3的哪个版本（他们之前是下载到本地进行管理的），我这边暂时还没找到，当时倒是看到过，确实移除了这个结构体
![1646966983(1)](https://user-images.githubusercontent.com/28774023/157794823-d748072d-b521-44c6-9426-b485bbfb0e8a.jpg)
![1646967614(1)](https://user-images.githubusercontent.com/28774023/157794827-3d29a5fd-e05d-42e8-a9d6-099b3df5ce78.jpg)

**Comment by speauty** [comment]
![1646968362(1)](https://user-images.githubusercontent.com/28774023/157795335-e3774c70-1277-44a3-a812-69585ba095f1.jpg)

**Comment by speauty** [comment]
> 请贴一下你使用的v3版本号，我去查一下。通常我们是不允许不兼容的参数修改的，v3到v1只是tag变化，接口的参数还是维持兼容的。

这儿有个commitId：0d6398e0，希望对你有所帮助
