### ISSUE TITLE
found package github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile in multiple modules

### ISSUE THREAD

**Issue by ghost** [TencentCloud/tencentcloud-sdk-go#185]
![image](https://user-images.githubusercontent.com/52640622/159697085-75c5965d-fc3b-420a-89af-0f9d261559e4.png)
v3.0是不兼容的，不知道为啥在go mod tidy之后会引用这个版本，请修复这个问题。
这导致我引用其他版本时引发错误。

我必须在go.mod中replace包版本才可以执行，这相当麻烦，我们所有项目都需要修改，这应该是你们的bug。

**Comment by hlbbt** [comment]
你们的cos服务、无法与短信服务、图形验证码服务兼容，会拉取下来冲突的包

**Comment by sesky4** [comment]
see #180
