### ISSUE TITLE
Dnspod 获取域名接口不好用

### ISSUE THREAD

**Issue by in64** [TencentCloud/tencentcloud-sdk-go#187]
复现方式：
lego 申请证书失败
https://go-acme.github.io/lego/dns/tencentcloud/
`lego --email x@example.com --dns dnspod --domains x@exapmle.com run`

**Comment by zqfan** [comment]
抱歉，sdk只是对dnspod提供接口的封装，申请证书失败需要联系dnspod处理哈，请到腾讯云官网控制台提工单给到dnspod产品咨询
