### ISSUE TITLE
taskId should be string acc to doc

### ISSUE THREAD

**Issue by BusyOppo** [TencentCloud/tencentcloud-sdk-go#189]
https://github.com/TencentCloud/tencentcloud-sdk-go/blob/0d3568a156f95a4a06cbdfd9a5e6b5eecfc136db/tencentcloud/vpc/v20170312/models.go#L9767

https://cloud.tencent.com/document/api/215/59037

**Comment by zqfan** [comment]
文档中的接口是DescribeVpcTaskResult，对应的代码是https://github.com/TencentCloud/tencentcloud-sdk-go/blob/0d3568a156f95a4a06cbdfd9a5e6b5eecfc136db/tencentcloud/vpc/v20170312/models.go#L10381
