### ISSUE TITLE
这短信发送代码写得也太丑了吧

### ISSUE THREAD

**Issue by wzhsh90** [TencentCloud/tencentcloud-sdk-go#194]
type DescribeTemplateListStatus struct {

	// 模板ID。
	TemplateId *uint64 `json:"TemplateId,omitempty" name:"TemplateId"`

	// 是否国际/港澳台短信，其中0表示国内短信，1表示国际/港澳台短信。
	International *uint64 `json:"International,omitempty" name:"International"`

	// 申请模板状态，其中0表示审核通过，1表示审核中，-1表示审核未通过或审核失败。
	StatusCode *int64 `json:"StatusCode,omitempty" name:"StatusCode"`

	// 审核回复，审核人员审核后给出的回复，通常是审核未通过的原因。
	ReviewReply *string `json:"ReviewReply,omitempty" name:"ReviewReply"`

	// 模板名称。
	TemplateName *string `json:"TemplateName,omitempty" name:"TemplateName"`

	// 提交审核时间，UNIX 时间戳（单位：秒）。
	CreateTime *uint64 `json:"CreateTime,omitempty" name:"CreateTime"`

	// 模板内容。
	TemplateContent *string `json:"TemplateContent,omitempty" name:"TemplateContent"`
}
定义的model 全是 * ，这是什么造型呢？

**Comment by zqfan** [comment]
指针主要是用来区分字段有没有设置值，如果不用指针可能实际没值但是给了默认值，但是默认值是有意义的，导致发生预料外的情况

**Comment by wzhsh90** [comment]
如果有你说的那些业务问题，你们也应该再封装一个数据层，而不是这样直接抛给使用者。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TencentCloud/tencentcloud-sdk-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月9日(星期一) 上午10:53
***@***.***&gt;;
抄送:&nbsp;"@***@***.******@***.***&gt;;
主题:&nbsp;Re: [TencentCloud/tencentcloud-sdk-go] 这短信发送代码写得也太丑了吧 (Issue #194)





 
指针主要是用来区分字段有没有设置值，如果不用指针可能实际没值但是给了默认值，但是默认值是有意义的，导致发生预料外的情况

**Comment by sesky4** [comment]
针对这些问题提供了一些工具函数，在 github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common： Common.StringPtr, Common.IntPtr ...
