### ISSUE TITLE
go: github.com/tencentcloud/tencentcloud-sdk-go@v3.0.97+incompatible: invalid version: unknown revision v3.0.97

### ISSUE THREAD

**Issue by maolinglinux** [TencentCloud/tencentcloud-sdk-go#200]
go: github.com/tencentcloud/tencentcloud-sdk-go@v3.0.97+incompatible: invalid version: unknown revision v3.0.97

**Comment by sesky4** [comment]
v3 is deprecated, please use v1.0.xxx .
<img width="924" alt="image" src="https://user-images.githubusercontent.com/13792533/180720665-d11cefc8-c3f1-4142-81d8-9fe394411e19.png">

As for now v1.0.449 is the latest version.
<img width="311" alt="image" src="https://user-images.githubusercontent.com/13792533/180720965-6c9eddbf-2dfd-445d-8569-4bd952477cb8.png">
