### ISSUE TITLE
cvm.SyncImagesRequest dose not return destination imageID

### ISSUE THREAD

**Issue by freesinger** [TencentCloud/tencentcloud-sdk-go#208]
Hi, i am using SDK to perform image-realted operations.

As title goes, it seems more proper to return destination imageID in response, since caller may save it for further use or check state of copied image. For now, I am not able to get copy status or new  imageId from `SyncImagesResponse` since it returns only requestID. Also, I can not assign `imageName` in request, which is not consistent with official documentation.

How can I get destination ImageId via SDK after calling `SyncImagesRequest`?

**Comment by zqfan** [comment]
I've contacted the CVM team for the ImageId issue long time ago, they said there is no plan for adding it in API response, so SDK cannot get it anyway. You can open a ticket in Tencent Cloud Management Console to CVM team, at least let them know the problem.

ImageName can be set in newer version of SDK, such as the latest version, https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/cvm/v20170312/models.go#L8533
