### ISSUE TITLE
请问scf包支持「获取函数单个请求运行状态」这个方法吗，打包压缩文件需用到了scf，但是是异步的需要轮询判断执行状态。

### ISSUE THREAD

**Issue by liangjunmo** [TencentCloud/tencentcloud-sdk-go#227]
获取函数单个请求运行状态：https://cloud.tencent.com/document/product/583/65348

<img width="826" alt="image" src="https://github.com/TencentCloud/tencentcloud-sdk-go/assets/123788114/4c73a8ef-da13-4eb3-85a7-9fcb694ed907">

**Comment by zqfan** [comment]
如果这个接口存在的话，需要scf先把对应的接口文档发布到官网后，SDK中才会有哈

**Comment by liangjunmo** [comment]
「发布到官网」，这个算是发布到官网了吗。

https://cloud.tencent.com/document/product/583/65348

<img width="1493" alt="image" src="https://github.com/TencentCloud/tencentcloud-sdk-go/assets/123788114/58cb7f1e-9bca-4cdd-bdc2-f3f34d3e8414">

**Comment by zqfan** [comment]
https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/scf/v20180416/client.go#L1914

**Comment by liangjunmo** [comment]
之前直接 `go get -v -u github.com/tencentcloud/tencentcloud-sdk-go/` 整个包，没看到`GetRequestStatus`方法。

按需安装后好了：

```
go get -v -u github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common

go get -v -u github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/scf
```

感谢回复。
