### ISSUE TITLE
DescribeSecurityGroupPolicies返回异常

### ISSUE THREAD

**Issue by jiangguoliang563** [TencentCloud/tencentcloud-sdk-go#24]
sgpRequest := vpc.NewDescribeSecurityGroupPoliciesRequest()
   sgpRequest.SecurityGroupId = v.SecurityGroupId
   // 通过client对象调用想要访问的接口，需要传入请求对象
   sgpResponse, err := client.DescribeSecurityGroupPolicies(sgpRequest)
   // 处理异常
   if _, ok := err.(*errors.TencentCloudSDKError); ok {
    fmt.Printf("An API error has returned: %s", err)
    return
   }
   // unexpected errors
   if err != nil {
    panic(err)
   }

panic: json: cannot unmarshal number into Go value of type string

**Comment by zqfan** [comment]
此问题已修复，如有复现，再重新打开
