### ISSUE TITLE
调用DescribeSlowLogs接口报错 ClientError.ParseJsonError, Message=Fail to parse json content:

### ISSUE THREAD

**Issue by zilidaxia** [TencentCloud/tencentcloud-sdk-go#246]
原因：because: json: cannot unmarshal number 2.14E-4 into Go struct field SlowLogInfoItem.LockTime of type int64

源码中type SlowLogInfoItem struct { // 锁时间,单位秒
	// 注意：此字段可能返回 null，表示取不到有效值。
	LockTime *int64 `json:"LockTime,omitnil" name:"LockTime"`
       ...}
为int64 而返回json是浮点型

**Comment by sesky4** [comment]
@zilidaxia 谢谢反馈，可以提供一个近期的 RequestId 吗，这可以帮助我们更快的排查到问题

**Comment by zilidaxia** [comment]
"RequestId":"00a14c17-9849-4933-b455-2d9dbbe6f47c"

**Comment by zilidaxia** [comment]
> @zilidaxia 谢谢反馈，可以提供一个近期的 RequestId 吗，这可以帮助我们更快的排查到问题

"RequestId":"00a14c17-9849-4933-b455-2d9dbbe6f47c"

**Comment by sesky4** [comment]
已经反馈给研发同学，是已知问题，在修复，谢谢反馈 !
