### ISSUE TITLE
SQLServer 产品类型咨询

### ISSUE THREAD

**Issue by kakaZhou719** [TencentCloud/tencentcloud-sdk-go#247]
看官网页面文档，SQLServer 产品类型有 ： "HA"，"RO", "SI"

<img width="993" alt="image" src="https://github.com/TencentCloud/tencentcloud-sdk-go/assets/83740799/de0805f1-e773-4c2e-ba8c-37e2a2fd6790">

但是我在使用的时候，这个字段出现了 "cvmHA" 

请问，这个是文档的错误还是？ "HA" 和"cvmHA" 的区别是什么？

**Comment by sesky4** [comment]
hi @kakaZhou719 ，我们对具体产品的使用方式并不清楚，这里主要是针对 Go SDK 本身的问题

针对某个具体的产品在腾讯云提交工单咨询可以获得更专业的回答

**Comment by zqfan** [comment]
> 看官网页面文档，SQLServer 产品类型有 ： "HA"，"RO", "SI"
> 
> <img alt="image" width="993" src="https://private-user-images.githubusercontent.com/83740799/290451613-de0805f1-e773-4c2e-ba8c-37e2a2fd6790.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NzIyODUsIm5iZiI6MTcwMjk3MTk4NSwicGF0aCI6Ii84Mzc0MDc5OS8yOTA0NTE2MTMtZGUwODA1ZjEtZTc3My00YzJlLWJhOGMtMzdlMmEyZmQ2NzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA3NDYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZjFkODAxMDUwMWUwZDMyOTQ3M2IwYmIxMzFlODQzYzQ5ZDQ1YjIyZjc2Mzg0M2YzMTY4Mjg0ZGE4ODdhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5QejTNUsL3Q3xIuk8yZtwrSETd9fn2Y6n8PFptao5YA">
> 但是我在使用的时候，这个字段出现了 "cvmHA"
> 
> 请问，这个是文档的错误还是？ "HA" 和"cvmHA" 的区别是什么？

在文档页面有一个反馈按钮，你可以直接点一下，然后截图圈中有疑问的地方，提交后该产品相关产研人员就会收到反馈了
