### ISSUE TITLE
账户中心的sdk，该从哪里获取呢？

### ISSUE THREAD

**Issue by xiaozhiliaoo** [TencentCloud/tencentcloud-sdk-go#256]
https://github.com/TencentCloud/tencentcloud-sdk-go/tree/master/tencentcloud/account

**Comment by zqfan** [comment]
需要这个产品先在官网有公开的接口文档发布，sdk中才会有对应的信息。
你可以看看访问管理cam产品下有没有你需要的账号相关的接口，https://cloud.tencent.com/document/product/598/33155

**Comment by xiaozhiliaoo** [comment]
> 账

谢谢🤝
