### ISSUE TITLE
DNSPod 批量创建记录不支持设置备注，明明有字段，显示不支持，然后调用批量更新记录，发现也不支持批量更新备注

### ISSUE THREAD

**Issue by serious-snow** [TencentCloud/tencentcloud-sdk-go#261]
type AddRecordBatch struct {
	// 记录备注(暂未支持)。
	Remark *string `json:"Remark,omitnil,omitempty" name:"Remark"`
}

type ModifyRecordBatchRequest struct {
	// 要修改的字段，可选值为 [“sub_domain”、”record_type”、”area”、”value”、”mx”、”ttl”、”status”] 中的某一个。
	Change *string `json:"Change,omitnil,omitempty" name:"Change"`
}

**Comment by sesky4** [comment]
@serious-snow hi，是调用后没有效果，还是返回了报错信息？

另外可以打开 `ClientProfile.Debug = true`，会在日志中打印发出的请求看看

**Comment by serious-snow** [comment]
> @serious-snow hi，是调用后没有效果，还是返回了报错信息？
> 
> 另外可以打开 `ClientProfile.Debug = true`，会在日志中打印发出的请求看看

是还不支持，所以请问一下有没有支持这方面的打算
1. 批量创建记录支持设置备注
或者
2. 批量更新记录支持更新备注字段

目前的场景就是 我添加了很多记录，想设置备注，只能单个单个的更新

**Comment by zqfan** [comment]
@serious-snow 这个需要dnspod产品的接口实现相关功能，这个sdk只是对接口能力的简单封装，目前还不具备提供接口能力外的功能。您可以到腾讯云官网控制台给dnspod产品提下需求。
