### ISSUE TITLE
关于 sdk域名解析问题的

### ISSUE THREAD

**Issue by Mrmanbanpai** [TencentCloud/tencentcloud-sdk-go#262]
近期在接入私有云 （使用的公有云 sdk）
设想是在请求的时候请求指定 ip 通过 http header Host 的形式做请求 但是看了一下 sdk 好像不允许这么做。domain 在初始化的时候被赋值了，并且计算 signature 处也处理了相关 Header 逻辑
有其他方案能让我使用这个 header 吗？ 或者服务端在分发的时候有备用 header 可以使用吗？

**Comment by zqfan** [comment]
sdk里的逻辑依赖Host头部，在公有云场景下，必须是个域名而不能是ip。不过你可以尝试下apigwendpoint的设置项，他的本意是通过一个网关类的代理实现请求公有云服务，也许也能适用于你的场景，原理是保持host头部的作用不变，但是发起请求的时候修改实际访问的地址，https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/common/client.go#L451

**Comment by Mrmanbanpai** [comment]
刚尝试了一下，理解这个功能，但是不适合我的场景。

我期望的还是不添加域名解析的前提下能找到请求的ip gw 应该是通过 host 做业务分发的。
我的理想状态是 请求
POST https://192.168.1.2
Host: clb.tencent.cloud.com 
X-TC-Action: Describexxx 
携带如上参数

这样签名的时候也是使用的仍然是业务 host。可以在业务层更方便的控制而不影响到相关的繁琐复杂的配置项。
类似这样的功能可以得到支持吗？

**Comment by sesky4** [comment]
@Mrmanbanpai 这样试试？

ClientProfile.HttpProfile.Endpoint = "192.168.1.2"
ClientProfile.HttpProfile.ApigwEndpoint = "clb.tencent.cloud.com"

**Comment by Mrmanbanpai** [comment]
> @Mrmanbanpai 这样试试？
> 
> ClientProfile.HttpProfile.Endpoint = "192.168.1.2"ClientProfile.HttpProfile.Endpoint =“192.168.1.2” ClientProfile.HttpProfile.ApigwEndpoint = "clb.tencentcloudapi.com"

不行，因为我实际访问的ApigwEndpoint是没被解析的内网域名。

根本问题是域名解析，想在请求的时候解决，这样不用每次部署的时候都去维护映射策略。

**Comment by Mrmanbanpai** [comment]
抱歉 是我的疏忽 这样形式是可以的。

**Comment by Mrmanbanpai** [comment]
> @Mrmanbanpai 这样试试？
> 
> ClientProfile.HttpProfile.Endpoint = "192.168.1.2"ClientProfile.HttpProfile.Endpoint =“192.168.1.2” ClientProfile.HttpProfile.ApigwEndpoint = "clb.tencentcloudapi.com"

对于apigw配置实现如下所示：
https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/common/client.go#L451

我应当如下使用此配置
cpf.HttpProfile.Endpoint = "vpc.tencentcloudapi.com"
cpf.HttpProfile.ApigwEndpoint = "127.0.0.1:8081"

并且在我本机启动一个简单服务端
```go
func main() {
	http.ListenAndServe(":8081", &handler{})
}

type handler struct{}
func (s *handler) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	fmt.Println(req.Host)
}
```

将 request.URL.Host 和request.Host 两值全部覆盖后 
本地服务端接受到的Host就是实际的ip值 也就是这个配置里的 127.0.0.1:8081

而当我仅覆盖request.URL.Host的值的时候 
本地服务端接收到的host值 vpc.tencentcloudapi.com
这种状态下我可以将我的指向公有云apigw的地址指向我的私有云地址 并且私有云的apigw可以正常进行分发

而在当前使用两值都覆盖的情况下 我即便请求了私有云的apigw地址 只会得到404的响应 。 
所以我期望的是在apigw覆盖的时候只覆盖当前的request.URL.Host即可

不知道我表述的足够清楚吗？

**Comment by sesky4** [comment]
@zqfan 看起来是这个修改 `request.URL.Host` 的步骤导致了问题

https://github.com/TencentCloud/tencentcloud-sdk-go/blob/1f58241c76b41454b830c4de60e1cb6ca0ee5cd7/tencentcloud/common/client.go#L452

似乎只修改 Host 头更合理?

**Comment by zqfan** [comment]
request.URL.Host是必须要修改的，指向的实际请求的地址。
request.Host 是因为apigw做转发时需要覆盖的特性要求。
前面让用户尝试apigw主要是看是否是同样的场景，但是目前来看，应该是只需要改实际请求的地址。如果目标是ip形式的，可以考虑修改hosts。否则用户只能尝试修改sdk的代码了

**Comment by Mrmanbanpai** [comment]
ok 那我没别的问题了 感谢
