### ISSUE TITLE
Hey, how about consider add a helper func for retry api?

### ISSUE THREAD

**Issue by stupidjohn** [TencentCloud/tencentcloud-sdk-go#27]
user may be tired of write retry logic.

**Comment by vincenthcui** [comment]
> user may be tired of write retry logic.

@stupidjohn new sdk comes with retry logic, see https://github.com/vincenthcui/awesome-tencentcloud-go

**Comment by zqfan** [comment]
v1.0.211 has added a retry logic for some specific scenarios
