### ISSUE TITLE
CreateLoadBalancer时SDK会自动给loadbalancername加上时间戳？

### ISSUE THREAD

**Issue by hiscal2015** [TencentCloud/tencentcloud-sdk-go#30]
Hi

发现通过SDK创建负载均衡器时，如果定义了负载均衡器名称，sdk会自动在名称后面加上一串字符（看上去像是时间戳？），这个逻辑似乎很不合理，可否修复？

![image](https://user-images.githubusercontent.com/15604715/52770013-f7974d00-306c-11e9-9cf3-858efb0d9752.png)

**Comment by hiscal2015** [comment]
发现使用python的sdk也有同样的问题

**Comment by zqfan** [comment]
sdk中并无这样的逻辑，可能是lb api本身的行为，待确定后再答复

**Comment by zqfan** [comment]
我已经向lb反馈过这个问题，并多次询问进展，但是看起来效果微弱，请到控制台工单系统给负载均衡（lb）提工单吧，这里继续讨论已无意义。请多理解。
