### ISSUE TITLE
yuntu api 3.0 require region not null

### ISSUE THREAD

**Issue by kimberw** [TencentCloud/tencentcloud-sdk-go#37]
I just use tencentcloud-sdk-go/tencentcloud/sts/v20180813/ in this project, but it not work well. it return an error 
`[TencentCloudSDKError] Code=MissingParameter, Message=The request is missing a required parameter `Region`.  `
I have read yuntu api 3.0, the Region is must require. but i don't really know how to make a default value for region. just like send a "ap-guangzhou", but region list only has "ap-beijing". Does this cause an exception? 
so may someone can append this in code.

**Comment by zqfan** [comment]
Can you provide the returned request id? and the action you requested. Currently I don't know what the problem you're facing, but region can be set when you initialize the client, you can pick up one region mentioned in the doc, or if "ap-beijing" is the only choice, use it.

**Comment by zqfan** [comment]
close it due to no response over 3 months, feel free to reopen it if there is any update.
