### ISSUE TITLE
尽快支持一下cls吧

### ISSUE THREAD

**Issue by xcaptain** [TencentCloud/tencentcloud-sdk-go#4]
准备用cls了，如果你这边能尽快出个官方的sdk，我就不用自己写了

**Comment by zqfan** [comment]
cls是指日志服务吗？目前日志服务不支持API3.0，因此sdk也就无法支持了。请到腾讯云控制台提单要求cls支持API3.0

**Comment by xcaptain** [comment]
原来是这样，我就说看文档接口调用格式很不一样呢，我先自己搞个简单的封装应下急，提单等你们弄完太慢了

**Comment by kidrocknroll** [comment]
+1

**Comment by zqfan** [comment]
日志服务目前仍未支持api3.0。这里先关掉issue，可以查看changelog获取最近更新信息
