### ISSUE TITLE
Consider using semantic version tags to enable go mod to use release tags.

### ISSUE THREAD

**Issue by nulldowntime** [TencentCloud/tencentcloud-sdk-go#44]
go mod relies on semantic versioning-compliant tags, which require a "v" at the beginning, as per: https://tip.golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

So go tooling would accept **v3.0.69**, but **3.0.69** is not compatible. 

Please consider using semantic versioning tags, either instead of or in addition to the current ones, so that go tooling can take advantage of releases.

**Comment by zqfan** [comment]
will consider it, thanks for reporting this issue.

**Comment by nulldowntime** [comment]
Hi, I see that there's **v**3.0.71 and **v**3.0.72, but not **v**3.0.73. I was hoping the good trend would continue!

**Comment by Sherlock-Holo** [comment]
agree, when I try `go get -u -v github.com/tencentcloud/tencentcloud-sdk-go@latest` , the version is `v3.0.89-0.20190927092845-9020bd75bf2b+incompatible`, it makes me confused if I download the latest version
