### ISSUE TITLE
细分返回的 API Error

### ISSUE THREAD

**Issue by likexian** [TencentCloud/tencentcloud-sdk-go#49]
目前仅API错误会返回TencentCloudSDKError，对于其它的比如网络错误、HTTP状态码异常、JSON错误能否区分一下Error类型，方便上层业务判断？

**Comment by zqfan** [comment]
implemented in https://github.com/TencentCloud/tencentcloud-sdk-go/commit/b19d5186e52fa505dc106977b7a551b5a7ae6525
will be included in next release
