### ISSUE TITLE
ic (v20190307) DescribeCards 查询卡片列表 类型错误

### ISSUE THREAD

**Issue by WLmutou** [TencentCloud/tencentcloud-sdk-go#50]
好多类型错误

```bash
 [TencentCloudSDKError] Code=ClientError.ParseJsonError, Message=Fail to parse json 
 : cannot unmarshal number into Go struct field  CardList.Total  of type string

 [TencentCloudSDKError] Code=ClientError.ParseJsonError, Message=Fail to parse json 
 : cannot unmarshal number into Go struct field  CardInfo.Sdkappid   of type string

 [TencentCloudSDKError] Code=ClientError.ParseJsonError, Message=Fail to parse json 
 : cannot unmarshal number into Go struct field CardInfo.ActivitedTime of type string

 [TencentCloudSDKError] Code=ClientError.ParseJsonError, Message=Fail to parse json 
 : cannot unmarshal number into Go struct field CardInfo.ProductExpiredTime of type string
```

![2019-08-15_17-32_1](https://user-images.githubusercontent.com/8075157/63087670-550d4780-bf85-11e9-92b2-7a815bf7ea15.png)
![2019-08-15_17-32](https://user-images.githubusercontent.com/8075157/63087671-550d4780-bf85-11e9-9a95-053a45645274.png)
![2019-08-15_17-29_1](https://user-images.githubusercontent.com/8075157/63087672-55a5de00-bf85-11e9-9e19-9cb919676c0a.png)
![2019-08-15_17-29](https://user-images.githubusercontent.com/8075157/63087673-55a5de00-bf85-11e9-841a-75e9fd5dcf3d.png)
![2019-08-15_17-27](https://user-images.githubusercontent.com/8075157/63087674-563e7480-bf85-11e9-9f69-f4fb41774d22.png)

**Comment by zqfan** [comment]
应该是产品后台返回的类型和官网文档申明不一致导致的，我们会通知负责产品进行尽快处理
