### ISSUE TITLE
client: HTTP Protocol is ignored

### ISSUE THREAD

**Issue by stevenh** [TencentCloud/tencentcloud-sdk-go#56]
The HttpProfile allows the protocol to be specified however the client ignores this and always uses `https://`
https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/common/profile/http_profile.go#L15
https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/common/http/request.go#L95

Also the correct verb for Protocol here should be Schema as defined by https://golang.org/pkg/net/url/#URL

**Comment by zqfan** [comment]
currently only https is valid in server side, http request will fail with response status code 403. The protocol attribute is defined for a rare case which is not available yet.
the verb issue will be fixed in following release, thanks for your report.

**Comment by stevenh** [comment]
Thanks for the feedback.

The reason we were changing the schema was for mocking, so https isn’t needed and adds quite a bit of complexity, so it we be good if this could be fixed too.
