### ISSUE TITLE
module cr does not compile

### ISSUE THREAD

**Issue by kaoet** [TencentCloud/tencentcloud-sdk-go#58]
```
# github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cr/v20180321
tencentcloud/cr/v20180321/models.go:534:8: undefined: binary
```

**Comment by zqfan** [comment]
fixed by https://github.com/TencentCloud/tencentcloud-sdk-go/commit/672c875e590ff232aa37c5e68adbfba8ad79bcb8
but  this commit just make sure compile can be done, the corresponding action/api still cannot be invoked correctly
