### ISSUE TITLE
why we use *string as field value rather than string

### ISSUE THREAD

**Issue by Colstuwjx** [TencentCloud/tencentcloud-sdk-go#59]
It's not convenient to set value as *string, like:

```
NetworkType *string
```

so what's the reason that we don't directly use `string`?
Thanks.

**Comment by zqfan** [comment]
For basic types, such as int, if its value is 0, we don't know if it is just set to 0 or not set, using pointers can allow us to check it. For string type, it is same for "" case (it is rare but still a valid case).
An alternative choce is add a flag to each attribute, we check the flag then use the value or not, it is not convenient as well and needs more lines of code.
