### ISSUE TITLE
wrong field type in  vpc.CreateRouteRequest struct

### ISSUE THREAD

**Issue by sinalpha** [TencentCloud/tencentcloud-sdk-go#6]
See this [pull reuest](https://github.com/TencentCloud/tencentcloud-sdk-go/pull/5) for detail.

**Comment by sinalpha** [comment]
same issue on the  [vpc.DeleteRoutesReques](https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/vpc/v20170312/models.go#L1015) struct

**Comment by zqfan** [comment]
It seems already fixed in recent releases, can you confirm it and close this issue? Thanks.
