### ISSUE TITLE
`vpc.DescribeNetworkInterfacesResponse` returned eni mac address is upper case

### ISSUE THREAD

**Issue by Colstuwjx** [TencentCloud/tencentcloud-sdk-go#60]
Hi team,

I have been used sdk go to call `vpc.DescribeNetworkInterfacesResponse` API, and it returned a list of enis. 

In order to find the main eni on the machine, I compares the mac address from api returned enis with the local nic, and found that api returned `52:54:00:32:63:8D`, and ifconfig shown mac address of local nic was `52:54:00:32:63:8d`, it's inconsistent.

Thanks.

**Comment by zqfan** [comment]
AFAIK, mac address is not case sensitive, just make it all lower case or upper case. For example, mac address in Windows operating system is all upper case. 
You can just convert the string to the format you like. 
And SDK itself cannot change the response from server side, please report a ticket in Tencent Cloud Management Console to VPC team for what you need.
Thanks.
