### ISSUE TITLE
一个参数为啥要用*string?老子用起来麻烦死了~为了效率？为了用起来爽？无语了，我就是来吐槽的！

### ISSUE THREAD

**Issue by OliverZou** [TencentCloud/tencentcloud-sdk-go#66]

**Comment by OliverZou** [comment]
我就想知道一个云客户端封装，不老老实实按常规方法做，这么做的出发点是什么，算我见识low，但我没见过golang的标准库里struct的成员这么用的。难不成需要固定的结构大小？需要嘛？你给我用最简单的方法初始化一个 []*string试试，原始数据是一个逗号分开的字串。别告诉我用json.Unmarshal，我的请求可没有json数据。

**Comment by zqfan** [comment]
可以参考下这个issue里的解释：https://github.com/TencentCloud/tencentcloud-sdk-go/issues/59
主要的问题是如果是值类型，那么当值是类型默认值的时候，我们无法区分这个值是被赋值了还是没有。例如一个字符串，初始化后是空字符串，但是空字符串也是一个有效的输入，数字类型也是一样，初始值是0，0也是有效的输入，所以都采用了指针类型。否则就得每个参数配一个标志位，标明这个值我设置了，而用户可能忘记有这个规则了，例如就是要指定Flag=0，但是忘了标记这个就是他的本意，这个值就不会传过去，而服务端的默认值是1，从而造成错误。

在这里提供了一些类型转换的函数，里面就有字符串数组转为字符串指针数组的方法：https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/common/types.go

还有另外一种做法是采用字符串（哪怕是个数字也是字符串），但是这样api就无法允许空字符串输入了，而腾讯云的部分api由于业务原因要求允许输入空字符串，我们无法识别后端的逻辑，所以也无法采用全部用字符串的方式。

对比下aws的sdk，也是采用这种方式，他们用户这么多，似乎也没遇到强烈的抵制，所以当时认为这样处理是能被开发者接受的。
受限于我们的知识和水平，还有腾讯云目前接口的现状，迫不得与采用这种方式，写起来麻烦点，体验不太好，还请见谅。
