### ISSUE TITLE
ClientProfile 支持毫秒设置

### ISSUE THREAD

**Issue by xxxsen** [TencentCloud/tencentcloud-sdk-go#67]
目前传进去的ReqTimeout 精度只能到秒, 建议支持传入time.Duration。

**Comment by zqfan** [comment]
请问具体的场景是什么呢？

超时时间一般到秒就够用了，考虑到https和一般接口耗时，一般也到不了一秒内。而且建议尽量不要自己设置超时使用sdk自带的，如果需要自己设置，也尽量设置大一点，例如30秒（因为部分接口由于业务逻辑本身就可能比较久）
