### ISSUE TITLE
建议调整默认httpClient的配置

### ISSUE THREAD

**Issue by xxxsen** [TencentCloud/tencentcloud-sdk-go#69]
默认的http client只保留2个空闲链接。 live.tencentcloudapi.com 域名解析出来应该只有一个vip(我这边拿到的是118.89.205.206), 当请求量比较大的时候, 会导致链接频繁创建销毁, 产生大量的TIME_WAIT, 所以这里建议调大MaxIdleConnsPerHost 的配置(例如50, 或者100)。

**Comment by zqfan** [comment]
Client有WithHttpTransport方法，可以指定自定义的transport实例，通过它你可以指定较大的空闲连接数量。
根据我们的观察，大部分用户的调用量并发并不大，不过也许调高默认值会友好点，但是到不了50或者100这个量级，我们考虑下。
