### ISSUE TITLE
 support token credential

### ISSUE THREAD

**Issue by zqfan** [TencentCloud/tencentcloud-sdk-go#7]
it seems new client is initialized only with secretid and secretkey, the token credential struct is never used.

**Comment by csrgxtu** [comment]
sdk有token的支持吗？毕竟官网的页面上说header里面可以放token

**Comment by zqfan** [comment]
> sdk有token的支持吗？毕竟官网的页面上说header里面可以放token

https://github.com/TencentCloud/tencentcloud-sdk-go/blob/master/tencentcloud/common/credentials.go#L16
