### ISSUE TITLE
ckafka: syntax error: unexpected literal `json:"Response"` 

### ISSUE THREAD

**Issue by firetaker** [TencentCloud/tencentcloud-sdk-go#81]
`D:\goworks\pkg\mod\github.com\tencentcloud\tencentcloud-sdk-go@v3.0.154+incompatible\tencentcloud\ckafka\v20190819\models.go:54:4: syntax error: unexpected literal `json:"Response"` after top level declaration
D:\goworks\pkg\mod\github.com\tencentcloud\tencentcloud-sdk-go@v3.0.154+incompatible\tencentcloud\ckafka\v20190819\models.go:65:4: syntax error: unexpected literal `json:"Response"` after top level declaration
D:\goworks\pkg\mod\github.com\tencentcloud\tencentcloud-sdk-go@v3.0.154+incompatible\tencentcloud\ckafka\v20190819\models.go:151:4: syntax error: unexpected literal `json:"Response"` after top level declaration
D:\goworks\pkg\mod\github.com\tencentcloud\tencentcloud-sdk-go@v3.0.154+incompatible\tencentcloud\ckafka\v20190819\models.go:1267:4: syntax error: unexpected literal `json:"Response"` after top level declaration
D:\goworks\pkg\mod\github.com\tencentcloud\tencentcloud-sdk-go@v3.0.154+incompatible\tencentcloud\ckafka\v20190819\models.go:1310:4: syntax error: unexpected literal `json:"Response"` after top level declaration
D:\goworks\pkg\mod\github.com\tencentcloud\tencentcloud-sdk-go@v3.0.154+incompatible\tencentcloud\ckafka\v20190819\models.go:1332:4: syntax error: unexpected literal `json:"Response"` after top level declaration
D:\goworks\pkg\mod\github.com\tencentcloud\tencentcloud-sdk-go@v3.0.154+incompatible\tencentcloud\ckafka\v20190819\models.go:1436:4: syntax error: unexpected literal `json:"Response"` after top level declaration
D:\goworks\pkg\mod\github.com\tencentcloud\tencentcloud-sdk-go@v3.0.154+incompatible\tencentcloud\ckafka\v20190819\models.go:1530:4: syntax error: unexpected literal `json:"Response"` after top level declaration
D:\goworks\pkg\mod\github.com\tencentcloud\tencentcloud-sdk-go@v3.0.154+incompatible\tencentcloud\ckafka\v20190819\models.go:1542:4: syntax error: unexpected literal `json:"Response"` after top level declaration
D:\goworks\pkg\mod\github.com\tencentcloud\tencentcloud-sdk-go@v3.0.154+incompatible\tencentcloud\ckafka\v20190819\models.go:1556:4: syntax error: unexpected literal `json:"Response"` after top level declaration
D:\goworks\pkg\mod\github.com\tencentcloud\tencentcloud-sdk-go@v3.0.154+incompatible\tencentcloud\ckafka\v20190819\models.go:1556:4: too many errors`

**Comment by zqfan** [comment]
thanks for reporting this issue, it will be fixed in next release
