### ISSUE TITLE
cms.TextModeration小部分返回TencentCloudSDKError

### ISSUE THREAD

**Issue by h1k0n** [TencentCloud/tencentcloud-sdk-go#86]
[TencentCloudSDKError] Code=ClientError.ParseJsonError, Message=Fail to parse json content: {\"Response\":{\"BusinessCode\":0,\"Data\":{\"BizType\":\"0\",\"Common\":{},\"DetailResult\":[{\"EvilLabel\":\"Ad\",\"EvilType\":20105,\"Keywords\":[\"qq\"],\"Score\":0}],\"EvilFlag\":0,\"EvilLabel\":\"Normal\",\"EvilType\":100,\"ID\":{},\"Keywords\":[\"qq\"],\"Label\":\"\",\"Res\":{},\"Suggestion\":\"Normal\"},\"RequestId\":\"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\"},\"retcode\":0,\"retmsg\":\"ok\"}\n, because: json: cannot unmarshal string into Go struct field TextData.Response.Data.BizType of type uint64, RequestId=

**Comment by zqfan** [comment]
这是因为接口定义BizType为数字，但是有时候返回了字符串。
SDK无法处理这种行为和定义不一致的情况。
请到控制台工单系统提单给cms反馈
