### ISSUE TITLE
云文档里面提供的Http访问接口的方式 与SDK中提供的接口，传入参数为什么不一致呢？？？

### ISSUE THREAD

**Issue by zxbfeng** [TencentCloud/tencentcloud-sdk-go#87]
![image](https://user-images.githubusercontent.com/7436339/88448312-1eb39a00-ce6f-11ea-872a-560169d2b09d.png)
这个描述的接口：1  没有找到对应的SDK接口  2.有个类似的SDK接口CreatePullStreamConfig, 但传递参数都不一致。比如创建任务的创建者这个参数前者有，后面没有，有点懵圈。

**Comment by zqfan** [comment]
sdk仅包含在官网文档上展示的接口，对于直播而言，就是展示在这里的接口，https://cloud.tencent.com/document/product/267/20456
