### ISSUE TITLE
[TencentCloudSDKError] Code=AuthFailure.InvalidAuthorization, Message=The request `Authorization` header does not conform to tencentcloud standards: `Service` in Credential not valid.

### ISSUE THREAD

**Issue by chenpfeisoo** [TencentCloud/tencentcloud-sdk-go#89]
[TencentCloudSDKError] Code=AuthFailure.InvalidAuthorization, Message=The request `Authorization` header does not conform to tencentcloud standards: `Service` in Credential not valid., RequestId=4188663f-43eb-421c-b53f-15566b063140

请问，这个授权问题怎么解决？

**Comment by zqfan** [comment]
endpoint别填ip

**Comment by chenpfeisoo** [comment]
没有填写ip，是域名

**Comment by zqfan** [comment]
复现下，client.WithDebug(true) 看看输出的头部信息是什么

**Comment by zqfan** [comment]
由于长时间未有反馈, 关闭此单. 如有新的信息, 可以重新打开
