### ISSUE TITLE
module ds not working

### ISSUE THREAD

**Issue by tfzxyinhao** [TencentCloud/tencentcloud-sdk-go#9]
![image](https://user-images.githubusercontent.com/444814/43823947-499e998a-9b23-11e8-85c9-aba6d1923441.png)

`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x5f862b]`

read from null pointer

**Comment by zqfan** [comment]
如果是返回不匹配的问题，我们增加了报错输出，可以明确是哪一个字段出问题了。如果可以复现，请重新贴一下报错输出。
