### ISSUE TITLE
[Request] api for cos service

### ISSUE THREAD

**Issue by dfang** [TencentCloud/tencentcloud-sdk-go#97]
竟然没有对象存储服务的API接口

**Comment by zqfan** [comment]
对象存储有自己的SDK：https://cloud.tencent.com/document/product/436/31215

**Comment by dfang** [comment]
应该整合到一起的

**Comment by zqfan** [comment]
两者使用风格其实并不一致，虽然未来如何并不确定，但是眼下其他几个语言的sdk正在做按产品拆分以减少sdk体积的事情

**Comment by dfang** [comment]
aws sdk go 那么多服务都不嫌大
